name: UNET_TF_1
channels:
  - defaults
dependencies:
  - python==3.6.13
  - scikit-image
  - numpy==1.15.0
  - opencv
  - cudnn==7.3.1
  - cudatoolkit=10.0.130
  - tensorflow-gpu==1.14.0
  - tensorflow==1.13.1

