name: TF_1
channels:
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.15.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - async_generator=1.10
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - ca-certificates=2023.12.12
  - certifi=2021.5.30
  - cffi=1.14.6
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.3.0
  - dataclasses=0.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.12.1
  - gast=0.5.3
  - grpcio=1.35.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2022.1.0
  - icu=58.2
  - imageio=2.9.0
  - intel-openmp=2023.1.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.17.0
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - lerc=3.0
  - libdeflate=1.17
  - libpng=1.6.39
  - libprotobuf=3.17.2
  - libtiff=4.5.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.5
  - notebook=6.4.3
  - olefile=0.46
  - openssl=1.1.1w
  - packaging=21.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.17.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - python=3.6.13
  - python-dateutil=2.8.2
  - pywavelets=1.1.1
  - pywin32=228
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtpy=2.0.1
  - scipy=1.5.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.41.2
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - tensorflow-gpu=1.13.1
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=4.3.3
  - typing_extensions=4.1.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.4.2
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - charset-normalizer==2.0.12
    - click==8.0.4
    - distlib==0.3.8
    - filelock==3.4.1
    - frozenlist==1.2.0
    - idna==3.7
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - msgpack==1.0.5
    - numpy==1.19.5
    - pandas==1.1.5
    - platformdirs==2.4.0
    - pytz==2024.1
    - ray==1.12.1
    - redis==4.3.6
    - requests==2.27.1
    - scikit-image==0.17.2
    - seaborn==0.11.2
    - tifffile==2020.9.3
    - urllib3==1.26.19
    - virtualenv==20.17.1
