name: UNET_TF_1
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - astor=0.8.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2021.5.30
  - cloudpickle=2.0.0
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.3.0
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=5.1.1
  - expat=2.4.9
  - ffmpeg=4.0
  - fontconfig=2.14.1
  - freeglut=3.0.0
  - freetype=2.12.1
  - glib=2.69.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - intel-openmp=2022.1.0
  - jasper=2.0.14
  - jpeg=9e
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=11.2.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - markdown=3.3.4
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - mock=4.0.3
  - ncurses=6.4
  - networkx=2.5
  - numpy-base=1.15.0
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - pcre=8.45
  - pillow=8.3.1
  - pixman=0.40.0
  - protobuf=3.17.2
  - py-opencv=3.4.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.6.13
  - python-dateutil=2.8.2
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.9.7
  - readline=8.2
  - scikit-image=0.14.1
  - scipy=1.1.0
  - sip=4.19.8
  - sqlite=3.40.1
  - tbb=2021.7.0
  - tbb4py=2021.3.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.1
  - typing_extensions=4.1.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-generator==1.10
    - attrs==22.1.0
    - backcall==0.2.0
    - bftools==0.4.0
    - bleach==4.1.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - clang==5.0
    - configargparse==1.7
    - connection-pool==0.0.3
    - datrie==0.8.2
    - defusedxml==0.7.1
    - docutils==0.18.1
    - entrypoints==0.4
    - filelock==3.4.1
    - flatbuffers==1.12
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.18
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.2
    - h5py==3.1.0
    - idna==3.4
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.2
    - jedi==0.17.2
    - jinja2==3.0.3
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.1
    - keras==2.2.3
    - markupsafe==2.0.1
    - mat4py==0.5.0
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.6
    - notebook==6.4.10
    - numpy==1.15.0
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==0.23.4
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pip==21.3.1
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.36
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pulp==2.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.13.0
    - pyrsistent==0.18.0
    - pytz==2022.7
    - pyzmq==24.0.1
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - ratelimiter==1.2.0.post0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - seaborn==0.11.1
    - send2trash==1.8.0
    - setuptools==59.6.0
    - six==1.15.0
    - smart-open==6.4.0
    - smmap==5.0.0
    - snakemake==6.15.5
    - stopit==1.1.2
    - tabulate==0.8.10
    - tensorflow-gpu==1.13.1
    - terminado==0.12.1
    - testpath==0.6.0
    - toposort==1.10
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.14
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.1
    - wrapt==1.15.0
